#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/bin/alist
CONFIG=/etc/alist/config.json

get_config() {
	config_get_bool enabled $1 enabled 1
	config_get port $1 port 5244
	config_get temp_dir $1 temp_dir "/tmp/alist"
	config_get ssl $1 ssl 0
	config_get ssl_cert $1 ssl_cert ""
	config_get ssl_key $1 ssl_key ""
}

start_service() {
	config_load alist
	config_foreach get_config alist
	[ $enabled != 1 ] && return 1
	mkdir -p $temp_dir
	if [ "$ssl" -eq 1 ];then
		SSL=true
	else
		SSL=false
	fi
	cat > $CONFIG <<EOF
{"force":false,"address":"0.0.0.0","port":$port,"jwt_secret":"","cdn":"","database":{"type":"sqlite3","host":"","port":0,"user":"","password":"","name":"","db_file":"/etc/alist/data.db","table_prefix":"x_","ssl_mode":""},"scheme":{"https":$SSL,"cert_file":"$ssl_cert","key_file":"$ssl_key"},"temp_dir":"$temp_dir","log":{"enable":false,"name":"$temp_dir/alist.log","max_size":10,"max_backups":5,"max_age":28,"compress":false}}
EOF
	procd_open_instance alist
	procd_set_param command $PROG
	procd_append_param command server --conf $CONFIG
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance alist
}

service_triggers() {
	procd_add_reload_trigger "alist"
}

reload_service() {
	stop
	start
}
